AUTHOR      = 'author'
AVATAR      = 'http://webfinger.net/rel/avatar'
HCARD       = 'http://microformats.org/profile/hcard'
LRDD        = 'lrdd'
PROFILE     = 'http://webfinger.info/rel/profile-page'
WEBFINGER   = 'http://webfinger.net/rel/acct-desc'
XFN         = 'http://gmpg.org/xfn/11'